-- 0001_initial_schema.sql
--
-- 정본: spec/backend/08-16-data-model.md 의 DDL 을 그대로 옮긴 것입니다.
-- **이 파일에서 스키마를 고치지 마세요.** 정본을 먼저 고치고, 바뀐 만큼만
-- 새 마이그레이션 파일을 더합니다 → ADR-019.
--
-- 테이블 14개 · PostgreSQL 방언 · 시각은 TIMESTAMPTZ (UTC 저장, Asia/Seoul 렌더)

BEGIN;

-- 적용 이력. 이 표가 있어야 무엇이 적용됐는지 알 수 있습니다
CREATE TABLE IF NOT EXISTS schema_migrations (
  version    TEXT          NOT NULL,
  applied_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  PRIMARY KEY (version)
);

CREATE FUNCTION touch_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE "case" (
  case_id        CHAR(26)      NOT NULL,   -- 정렬 가능한 식별자(ULID)
  track          TEXT          NOT NULL DEFAULT 'victim'
                 CHECK (track IN ('victim','frozen_account')),
                                           -- 피해자 / 통장묶기 → 03-channel-matrix.md
  status         TEXT          NOT NULL DEFAULT 'intake'
                 CHECK (status IN ('intake','in_progress','waiting','closed')),
  session_key_id CHAR(26)      NULL,       -- 볼트 세션키 식별자. 키 자체는 저장하지 않는다
  opened_at      TIMESTAMPTZ(3) NOT NULL,
  closed_at      TIMESTAMPTZ(3) NULL,
  purge_after    DATE          NOT NULL,   -- 이 날짜 이후 파기 대상
  created_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  PRIMARY KEY (case_id)
);

CREATE INDEX idx_case_status_purge ON "case" (status, purge_after);

CREATE TRIGGER trg_case_touch BEFORE UPDATE ON "case"
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE evidence (
  evidence_id   CHAR(26)      NOT NULL,
  case_id       CHAR(26)      NOT NULL,
  kind          TEXT          NOT NULL CHECK (kind IN ('audio','image','text')),
  object_key    VARCHAR(500)  NULL,       -- 객체 저장소 경로
  mime_type     VARCHAR(100)  NULL,
  byte_size     BIGINT        NULL,
  transcript_masked TEXT      NULL,       -- 토큰화된 전사·OCR 결과. 원문 금지
  ingest_status TEXT          NOT NULL DEFAULT 'pending'
                CHECK (ingest_status IN ('pending','processing','done','failed')),
  ingest_error  VARCHAR(255)  NULL,
  created_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  PRIMARY KEY (evidence_id),
  CONSTRAINT fk_evidence_case FOREIGN KEY (case_id)
    REFERENCES "case"(case_id) ON DELETE CASCADE
);

CREATE INDEX idx_evidence_case ON evidence (case_id, created_at);

CREATE TABLE case_channel (
  case_channel_id BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  case_id         CHAR(26)     NOT NULL,
  channel_id      VARCHAR(32)  NOT NULL,
                  -- CH-bank | CH-neobank | CH-securities | CH-easypay
                  -- CH-crypto | CH-facetoface | CH-giftcard | CH-carrier
                  -- 목록 검증은 코드가 합니다. CHECK 로 굳히지 않는 이유는 §4 참조
  org_id          VARCHAR(32)  NULL,       -- 기관 식별자. org 테이블 논리 참조. §4.1
  org_name_raw    VARCHAR(100) NULL,       -- 사용자·증거에 나온 표기 그대로.
                                           -- 토큰화 대상 아님 → ADR-011
  amount          NUMERIC(15,0) NULL,      -- 원 단위
  occurred_at     TIMESTAMPTZ(3) NULL,
  confidence      NUMERIC(3,2) NULL,       -- 판별 확신도 0.00~1.00
  source          TEXT         NOT NULL CHECK (source IN ('auto','user')),
                                           -- 자동 추출 / 문진 응답
  created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  PRIMARY KEY (case_channel_id),
  CONSTRAINT fk_channel_case FOREIGN KEY (case_id)
    REFERENCES "case"(case_id) ON DELETE CASCADE
);

CREATE INDEX idx_case_channel_case ON case_channel (case_id);

CREATE TABLE case_slot (
  case_slot_id BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  case_id      CHAR(26)      NOT NULL,
  slot_key     VARCHAR(64)   NOT NULL,   -- §5.1 목록의 이름만
  tier         TEXT          NOT NULL CHECK (tier IN ('T0','T1','T2')),
  value_masked TEXT          NULL,       -- 토큰화된 값. 원문 금지
  value_type   TEXT          NOT NULL
               CHECK (value_type IN ('datetime','decimal','string','enum','bool')),
  state        TEXT          NOT NULL DEFAULT 'empty'
               CHECK (state IN ('empty','extracted','confirmed','unknown')),
  source       TEXT          NULL CHECK (source IN ('auto','user','system')),
  source_ref   CHAR(26)      NULL,       -- 어느 evidence 에서 나왔는가
  confidence   NUMERIC(3,2)  NULL,
  created_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  PRIMARY KEY (case_slot_id),
  CONSTRAINT uk_case_slot UNIQUE (case_id, slot_key),
  CONSTRAINT fk_slot_case FOREIGN KEY (case_id)
    REFERENCES "case"(case_id) ON DELETE CASCADE
);

CREATE INDEX idx_case_slot_state ON case_slot (case_id, state);

CREATE TRIGGER trg_case_slot_touch BEFORE UPDATE ON case_slot
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE plan_step (
  plan_step_id  CHAR(26)      NOT NULL,
  case_id       CHAR(26)      NOT NULL,
  seq           INT           NOT NULL,   -- 표시 순서
  step_key      VARCHAR(64)   NOT NULL,   -- KB 절차 항목 식별자
  title         VARCHAR(255)  NOT NULL,
  actor         TEXT          NOT NULL
                CHECK (actor IN ('victim','police','bank','prosecutor','carrier','issuer')),
  body          JSONB         NOT NULL,   -- 단계 본문(설명·연락처·채널)
  conditional   VARCHAR(255)  NULL,       -- 슈퍼셋 플랜의 조건 라벨.
                                          -- 예: "카카오페이로 보냈다면"
  state         TEXT          NOT NULL DEFAULT 'not_started'
                CHECK (state IN ('not_started','in_progress','done_verified',
                                 'unconfirmed','skipped')),
  kb_entry_id   VARCHAR(64)   NOT NULL,   -- 논리 참조
  kb_version    VARCHAR(32)   NOT NULL,   -- 인용한 KB 버전
  source_url    VARCHAR(500)  NOT NULL,   -- 근거 링크. 비면 적재 거부
  effective_from DATE         NOT NULL,   -- 시행일. 비면 적재 거부
  generated_at  TIMESTAMPTZ(3) NOT NULL,
  done_at       TIMESTAMPTZ(3) NULL,
  created_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  PRIMARY KEY (plan_step_id),
  CONSTRAINT uk_case_step UNIQUE (case_id, step_key),
  CONSTRAINT fk_step_case FOREIGN KEY (case_id)
    REFERENCES "case"(case_id) ON DELETE CASCADE
);

CREATE INDEX idx_plan_step_state ON plan_step (case_id, state);

CREATE TRIGGER trg_plan_step_touch BEFORE UPDATE ON plan_step
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE artifact (
  artifact_id   CHAR(26)      NOT NULL,
  plan_step_id  CHAR(26)      NOT NULL,
  case_id       CHAR(26)      NOT NULL,   -- 조회 편의를 위한 비정규화
  kind          TEXT          NOT NULL
                CHECK (kind IN ('receipt_no','sms_capture','receipt_doc','other')),
  value_masked  VARCHAR(255)  NULL,       -- 접수번호 등. 토큰화 후 저장
  object_key    VARCHAR(500)  NULL,       -- 업로드 캡처·서류의 객체 저장소 경로
  verify_level  TEXT          NOT NULL CHECK (verify_level IN ('L1','L2','L3')),
  verify_result TEXT          NOT NULL
                CHECK (verify_result IN ('passed','failed','not_applicable')),
  verify_detail JSONB         NULL,       -- 포맷 체크·OCR 대조 결과. PII 금지
  created_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  PRIMARY KEY (artifact_id),
  CONSTRAINT fk_artifact_step FOREIGN KEY (plan_step_id)
    REFERENCES plan_step(plan_step_id) ON DELETE CASCADE
);

CREATE INDEX idx_artifact_step ON artifact (plan_step_id);
CREATE INDEX idx_artifact_case ON artifact (case_id);

CREATE TABLE deadline (
  deadline_id   CHAR(26)      NOT NULL,
  case_id       CHAR(26)      NOT NULL,
  plan_step_id  CHAR(26)      NULL,       -- 어느 단계의 기한인가
  kind          TEXT          NOT NULL CHECK (kind IN ('primary','grace','info')),
                                          -- 본 기한 / 유예 / 안내용(공고 2개월 등)
  due_at        TIMESTAMPTZ(3) NOT NULL,
  computed_from VARCHAR(64)   NOT NULL,   -- 기산점이 된 slot_key 또는 artifact
  computed_at   TIMESTAMPTZ(3) NOT NULL,
  rule_snapshot JSONB         NOT NULL,   -- 계산에 쓴 KB 항목 전체 + 반영한 공휴일
  kb_version    VARCHAR(32)   NOT NULL,
  status        TEXT          NOT NULL DEFAULT 'open'
                CHECK (status IN ('open','met','missed','void')),
  created_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  PRIMARY KEY (deadline_id),
  CONSTRAINT fk_deadline_case FOREIGN KEY (case_id)
    REFERENCES "case"(case_id) ON DELETE CASCADE
);

CREATE INDEX idx_deadline_case ON deadline (case_id);
CREATE INDEX idx_deadline_due  ON deadline (status, due_at);

CREATE TRIGGER trg_deadline_touch BEFORE UPDATE ON deadline
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE message (
  message_id     CHAR(26)      NOT NULL,
  case_id        CHAR(26)      NOT NULL,
  turn_no        INT           NOT NULL,
  role           TEXT          NOT NULL
                 CHECK (role IN ('user','assistant','system')),
  content_masked TEXT          NOT NULL,  -- 토큰화된 본문. 원문 금지
  masked_counts  JSONB         NULL,      -- 유형별 토큰화 건수
  kb_context_refs JSONB        NULL,      -- 이 턴 프롬프트에 넣은 KB 항목의 식별자만.
                                          -- [{kb_entry_id, kb_version}, …]
                                          -- 본문을 저장하지 않는다 → §9.1
  citations      JSONB         NULL,      -- 답변이 가리킨 자료 목록. kb-/case-/t- 가 섞인다.
                                          -- kb_entry_id 는 kb- 항목에만 → §9.3
  insufficient   BOOLEAN       NOT NULL DEFAULT FALSE,
                                          -- 모델이 근거 없음을 선언했는가.
                                          -- true 면 슬롯 질문으로 넘어갔다 → §9.3
  prompt_masked  TEXT          NULL,      -- 이 턴에 실제로 보낸 프롬프트 전문.
                                          -- 토큰화 상태. 관리자 조회용 → §9.2
  reasoning_masked TEXT        NULL,      -- 모델이 낸 판단 근거. 토큰화 상태.
                                          -- 사용자 응답에 내보내지 않는다 → §9.2
  model_name     VARCHAR(64)   NULL,
  token_in       INT           NULL,
  token_out      INT           NULL,
  latency_ms     INT           NULL,
  created_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  PRIMARY KEY (message_id),
  CONSTRAINT uk_case_turn UNIQUE (case_id, turn_no, role),
  CONSTRAINT fk_message_case FOREIGN KEY (case_id)
    REFERENCES "case"(case_id) ON DELETE CASCADE
);

CREATE INDEX idx_message_case ON message (case_id, created_at);

CREATE TABLE audit_log (
  audit_id    CHAR(26)      NOT NULL,
  case_id     CHAR(26)      NULL,
  event_type  VARCHAR(64)   NOT NULL,
  actor_type  TEXT          NOT NULL
              CHECK (actor_type IN ('user','system','model')),
  detail      JSONB         NOT NULL,   -- PII 금지. 원문도 토큰도 넣지 않는다
  prev_hash   CHAR(64)      NULL,
  hash        CHAR(64)      NOT NULL,   -- SHA-256
  created_at  TIMESTAMPTZ(6) NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (audit_id)
);

CREATE INDEX idx_audit_case_time ON audit_log (case_id, created_at);
CREATE INDEX idx_audit_type_time ON audit_log (event_type, created_at);

CREATE TABLE kb_entry (
  kb_entry_id    VARCHAR(64)   NOT NULL,  -- 이 KB 항목의 식별자
  kb_version     VARCHAR(32)   NOT NULL,
  step_key       VARCHAR(64)   NOT NULL,  -- 절차 단계 식별자. 우선순위 병합의 키.
                                          -- plan_step.step_key 와 같은 값
  step_seq       INT           NOT NULL,  -- 기본 표시 순서. 유형마다 다를 수 있다.
                                          -- CH-facetoface 는 순서가 역전된다
  channel_id     VARCHAR(32)   NULL,      -- CH-xxx. NULL 이면 전 유형 공통
  org_id         VARCHAR(32)   NULL,      -- 기관 전용 항목. NULL 이면 유형 기본
  track          TEXT          NOT NULL DEFAULT 'victim'
                 CHECK (track IN ('victim','frozen_account')),
  title          VARCHAR(255)  NOT NULL,
  body           JSONB         NOT NULL,
  legal_basis    VARCHAR(500)  NOT NULL,
  source_url     VARCHAR(500)  NOT NULL,
  effective_from DATE          NOT NULL,
  effective_until DATE         NULL,      -- NULL 이면 현재 유효
  verified_at    DATE          NOT NULL,  -- Staleness Guard 90일 기준
  released_at    TIMESTAMPTZ(3) NOT NULL,
  PRIMARY KEY (kb_entry_id, kb_version)
);

CREATE INDEX idx_kb_entry_lookup ON kb_entry
  (track, channel_id, org_id, step_key, effective_from, effective_until);
CREATE INDEX idx_kb_entry_verified ON kb_entry (verified_at);

CREATE TABLE org (
  org_id      VARCHAR(32)   NOT NULL,   -- 예: kb-bank, kakaopay, upbit
  channel_id  VARCHAR(32)   NOT NULL,   -- 이 기관이 속한 유형
  name        VARCHAR(100)  NOT NULL,   -- 정식 표기. 예: 국민은행
  aliases     JSONB         NOT NULL,   -- 별칭 목록. 매칭에 쓴다
  contact     JSONB         NOT NULL,   -- 콜센터·앱 경로·영업점 안내
  source_url  VARCHAR(500)  NOT NULL,   -- 연락처 근거. 비면 적재 거부
  verified_at DATE          NOT NULL,
  kb_version  VARCHAR(32)   NOT NULL,
  PRIMARY KEY (org_id, kb_version)
);

CREATE INDEX idx_org_channel ON org (channel_id);

CREATE TABLE source_snapshot (
  snapshot_id   CHAR(26)      NOT NULL,
  source_type   TEXT          NOT NULL
                CHECK (source_type IN ('law','pre_notice','press','manual')),
  source_key    VARCHAR(255)  NOT NULL,  -- law:    법령ID:조문번호:조문가지번호
                                         -- press:  게시글 URL
                                         -- manual: org_id:field
  fetched_at    TIMESTAMPTZ(3) NOT NULL,
  content       TEXT          NOT NULL,  -- 원문 그대로
  content_hash  CHAR(64)      NOT NULL,  -- SHA-256
  meta          JSONB         NOT NULL,  -- 시행일·공포일·부처·게시일 등
  PRIMARY KEY (snapshot_id),
  CONSTRAINT uk_source_hash UNIQUE (source_key, content_hash)
);

CREATE INDEX idx_source_snapshot_time ON source_snapshot (source_key, fetched_at);

CREATE TABLE source_change (
  change_id       CHAR(26)      NOT NULL,
  source_key      VARCHAR(255)  NOT NULL,
  snapshot_before CHAR(26)      NULL,     -- 최초 수집이면 NULL
  snapshot_after  CHAR(26)      NOT NULL,
  detected_at     TIMESTAMPTZ(3) NOT NULL,
  dedupe_key      VARCHAR(255)  NULL,     -- 같은 제도 변경을 묶는 키.
                                          -- 예: law:011359:3 · topic:crypto-relief-202610
  impact          JSONB         NULL,     -- LLM 영향 분석:
                                          -- 어느 kb_entry 에 영향? 확신도? 개정 초안
  review_status   TEXT          NOT NULL DEFAULT 'pending'
                  CHECK (review_status IN ('pending','approved','rejected','deferred')),
  reviewed_by     VARCHAR(64)   NULL,
  reviewed_at     TIMESTAMPTZ(3) NULL,
  review_note     TEXT          NULL,
  released_version VARCHAR(32)  NULL,     -- 승인 후 반영된 KB 버전
  PRIMARY KEY (change_id)
);

CREATE INDEX idx_source_change_status ON source_change (review_status, detected_at);
CREATE INDEX idx_source_change_dedupe ON source_change (dedupe_key);

CREATE TABLE source_registry (
  source_key_prefix VARCHAR(255) NOT NULL, -- 예: law.go.kr/DRF · fsc.go.kr/no010101
  source_type       TEXT         NOT NULL
                    CHECK (source_type IN ('law','pre_notice','press','manual')),
  watch_method      TEXT         NOT NULL
                    CHECK (watch_method IN ('api','rss','board','human')),
  interval_days     INT          NULL,     -- human 이면 NULL
  last_success_at   TIMESTAMPTZ(3) NULL,
  last_seen_date    DATE         NULL,     -- board: 마지막으로 수집한 게시물 날짜
  last_error        VARCHAR(500) NULL,
  PRIMARY KEY (source_key_prefix)
);

INSERT INTO schema_migrations (version) VALUES ('0001_initial_schema')
  ON CONFLICT (version) DO NOTHING;

COMMIT;
